### ISSUE TITLE
Bridge fails to publish messages

### ISSUE THREAD

**Issue by martykube** [vert-x3/vertx-tcp-eventbus-bridge#9]
### Version

* vert.x core: 3.2.1
* vert.x tcp eventbus bridge: 3.2.1

### Context
After receiving the register message the TCP Bridge throws an exception on every attempt to publish a message:

Apr 15, 2016 8:52:03 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.ClassCastException: java.lang.String cannot be cast to io.vertx.core.json.JsonObject
    at io.vertx.ext.eventbus.bridge.tcp.impl.TcpEventBusBridgeImpl.lambda$null$4(TcpEventBusBridgeImpl.java:194)
    at io.vertx.core.eventbus.impl.HandlerRegistration.handleMessage(HandlerRegistration.java:207)
    at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:201)
    at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$127(EventBusImpl.java:498)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)

### Do you have a reproducer?

https://github.com/martykube/Vertx-TCP-Event-Bus-Bridge-Example

### Steps to reproduce

1.Start vertx with "gradle execute"
2. Run the python client which, 1) connects, 2) pings, and 3) sends a register request
3. Every attempt to publish the message causes the bridge to throw the exception

### Extra

* FrameHelper line 31 and 47 seems to imply that all message bodies are JSON.  Does that have to be true?

**Comment by martykube** [comment]
I was able to make the exception go away by changing

> vertx.eventBus().publish("pcs.status", "{\"foo\":\"bar\"}");

to 

>  vertx.eventBus().publish("pcs.status", new JsonObject("{\"foo\":\"bar\"}"));

I looks like the code assumes every message payload has to be a JsonObject.  I would have thought strings are okay as payload.

**Comment by cescoffier** [comment]
I think this is the "normal" behavior. In java to send a `JsonObject`, you need to create a new `JsonObject`. If you send a `String` containing some json, it would be a `String`.

**Comment by martykube** [comment]
Sending a JsonObject worked fine.  I can't send a String containing json.

**Comment by cescoffier** [comment]
Byte array should be wrapped in a `io.vertx.core.Buffer`. Objects need to be serialized to json. Primitive types are sent as they are. You can implement your own codec as in https://github.com/vert-x3/vertx-examples/blob/master/core-examples/src/main/java/io/vertx/example/core/eventbus/messagecodec/util/CustomMessageCodec.java.

**Comment by martykube** [comment]
Okay, fair enough, I'll close this one.  Thanks for the advice!
